apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/api-replicas.yaml
  - path: patches/ui-replicas.yaml

# En prod: imágenes con un tag específico (actualizado por Jenkins)
images:
  - name: gjisus/golabs-api
    newTag: latest
  - name: gjisus/golabs-ui
    newTag: latest
