apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golabs-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: golabs
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: golabs

  source:
    repoURL: https://github.com/BadByte-Team/golabs-infra.git
    targetRevision: main
    path: k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: golabs

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
