apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/api-replicas.yaml
  - path: patches/ui-replicas.yaml

# En dev: imágenes con tag 'dev'
images:
  - name: gjisus/golabs-api
    newTag: dev
  - name: gjisus/golabs-ui
    newTag: dev
