apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/api-replicas.yaml
  - path: patches/ui-replicas.yaml

# Tag actualizado automáticamente por Jenkins CI
images:
  - name: gjisus/golabs-api
    newTag: latest # golabs-api
  - name: gjisus/golabs-ui
    newTag: latest # golabs-ui
