apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/api-replicas.yaml
  - path: patches/ui-replicas.yaml

# Tag actualizado automáticamente por Jenkins CI
images:
  - name: gutsnet/golabs-api
    newTag: ctf # golabs-api
  - name: gutsnet/golabs-ui
    newTag: ctf-3 # golabs-ui
  - name: gutsnet/golabs-static
    newTag: ctf # golabs-static
