apiVersion: v1
kind: Service
metadata:
  name: golabs-static
  namespace: golabs
  labels:
    app.kubernetes.io/name: golabs-static
    app.kubernetes.io/component: static-site
    app.kubernetes.io/part-of: golabs
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: golabs-static
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30082 # Accesible en http://<IP_EC2>:30082
      protocol: TCP
